### ISSUE TITLE
Error while creating a child theme with style.css only

### ISSUE THREAD

**Issue by ahazem** [jonathandean/On-The-Rocks#1]
Hey,

I have just stumbled upon this minor issue while creating a child theme based on your theme, it seems like the `load_theme_options` hook inside the parent theme's `functions.php` file is trying to require the `theme_options.php` file (not present in the child theme, as you could guess) which outputs the following error:

``` php
Warning: require_once(/Users/****/Sites/ragel/wp-content/themes/manchesters-girl/theme-options.php) [function.require-once]: failed to open stream: No such file or directory in /Users/****/Sites/ragel/wp-content/themes/on-the-rocks/functions.php on line 31

Fatal error: require_once() [function.require]: Failed opening required '/Users/****/Sites/ragel/wp-content/themes/manchesters-girl/theme-options.php' (include_path='.:') in /Users/****/Sites/ragel/wp-content/themes/on-the-rocks/functions.php on line 31
```

I simply added the `theme-options.php` file to my child theme and everything worked fine. However, I believe `functions.php` should not register that hook unless such a file do really exist in the child theme directory. What do you think?

**Comment by jonathandean** [comment]
Hi @ahazem, thanks for catching! I will add a note to take a look at that. I still have a fair amount of general clean up I should do now that people are actually looking at it! :)
